import { z } from "zod";
import { MonsterTemplateSchema, type MonsterTemplate } from "./type.monster-template.js";
import { MonsterStatsLevelRange, type MonsterStatsLevelRange as MonsterStatsLevelRangeKey } from "./type.monster-stats.js";
import { getMonsterStatsLevelRange } from "./util.monster-stats.js";

const DEFAULT_TEMPLATE_TIMESTAMP = 0;

export const DefaultMonsterTemplates = z.record(MonsterStatsLevelRange, z.array(MonsterTemplateSchema));
export type DefaultMonsterTemplates = z.infer<typeof DefaultMonsterTemplates>;

export function getDefaultMonsterTemplatesForLevel(level: number): MonsterTemplate[] {
  const levelRange = getMonsterStatsLevelRange(level);
  return DEFAULT_MONSTER_TEMPLATES[levelRange] ?? [];
}

export function getDefaultMonsterTemplatesForRange(levelRange: MonsterStatsLevelRangeKey): MonsterTemplate[] {
  return DEFAULT_MONSTER_TEMPLATES[levelRange] ?? [];
}

export const DEFAULT_MONSTER_TEMPLATES: DefaultMonsterTemplates = {
  levels_1_2: [
    {
      id: "default-levels-1-2-goblin-spearmen",
      name: "Goblin Spearmen",
      monsterType: "soldier",
      initiative: 3,
      maxHp: 8,
      notes: "Polearm, Throw Small, cowardly goblins that hurl crude javelins from the shadows before fleeing.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-goblin-scout",
      name: "Goblin Scout",
      monsterType: "soldier",
      initiative: 3,
      maxHp: 8,
      notes: "Ranged (2d4) Sneaky goblins that shoot small bows from the hidden places.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-goblin-rider",
      name: "Goblin Rider",
      monsterType: "soldier",
      initiative: 3,
      maxHp: 8,
      notes: "Mounted, Polearm Move (8,2) Goblins astride mangy wolves, charging with spears to harry adventurers.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-goblin-chieftain",
      name: "Goblin Chieftain",
      monsterType: "commander",
      initiative: 5,
      maxHp: 15,
      notes: "Heroic (2), Command A grizzled goblin barking orders, wielding a spear to direct ambushes.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-goblin-shaman",
      name: "Goblin Shaman",
      monsterType: "leader",
      initiative: 8,
      maxHp: 10,
      notes: "Mage (4) Cackling goblins casting crude spells that erupt in chaotic bursts.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-orc-soldier",
      name: "Orc Soldier",
      monsterType: "brute",
      initiative: 1,
      maxHp: 14,
      notes: "Strike, Health (14), Tough (3) Hulking warriors with crude axes, delivering crushing blows in melee.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-kobold-mangler",
      name: "Kobold Mangler",
      monsterType: "soldier",
      initiative: 3,
      maxHp: 8,
      notes: "Move (5/4) Shifty kobolds armed with knives and spears",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-kobold-slinger",
      name: "Kobold Slinger",
      monsterType: "soldier",
      initiative: 3,
      maxHp: 8,
      notes: "Move (5/4), Ranged Scrawny kobolds armed with slings, pelting foes from a safe distance.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-shambling-skeleton",
      name: "Shambling Skeleton",
      monsterType: "minion",
      initiative: 2,
      maxHp: 4,
      notes: "Skeletal Brittle undead that shamble forward, resilient to arrows despite their frailty.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-skeleton-warrior",
      name: "Skeleton Warrior",
      monsterType: "soldier",
      initiative: 3,
      maxHp: 8,
      notes: "Skeletal, Strike Armed with rusty swords, these undead lash out tirelessly, tough against piercing blows.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-zombie",
      name: "Zombie",
      monsterType: "minion",
      initiative: 2,
      maxHp: 12,
      notes: "Health (12), Move (4,0) Armed with rusty swords, these undead lash out tirelessly, tough against piercing blows.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-bat",
      name: "Bat",
      monsterType: "minion",
      initiative: 2,
      maxHp: 4,
      notes: "Fly Tiny, bat-like creatures that swarm from above, draining blood with needle-like proboscises.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-wolf",
      name: "Wolf",
      monsterType: "beast",
      initiative: 6,
      maxHp: 8,
      notes: "Move (5,4) Furious pack animal looking for vulnerable prey.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-giant-rat",
      name: "Giant Rat",
      monsterType: "minion",
      initiative: 2,
      maxHp: 4,
      notes: "Strike Filthy rodents that dart in for quick bites, overwhelming prey in swarms.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-giant-centipede",
      name: "Giant Centipede",
      monsterType: "beast",
      initiative: 6,
      maxHp: 8,
      notes: "Strike, Climber Multi-legged horrors that skitter up walls to deliver venomous bites.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-spider",
      name: "Spider",
      monsterType: "minion",
      initiative: 2,
      maxHp: 4,
      notes: "Climber Wall-crawling arachnids that leap to ensnare prey with venomous fangs.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-spider-brood-mother",
      name: "Spider Brood mother",
      monsterType: "slayer",
      initiative: 7,
      maxHp: 7,
      notes: "Climber, Strike Wall-crawling arachnid mother that sends her spawn to ensnare prey with venomous fangs.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-1-2-ogre",
      name: "Ogre",
      monsterType: "behemoth",
      initiative: 1,
      maxHp: 30,
      notes: "Devastating strike Health (30) Towering brutes swinging tree-trunk clubs, smashing anything in reach.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
  ],
  levels_3_4: [
    {
      id: "default-levels-3-4-orc-warrior",
      name: "Orc Warrior",
      monsterType: "soldier",
      initiative: 3,
      maxHp: 11,
      notes: "Strike A battle-hardened orc wielding a heavy axe, ready to cleave through foes with extra attacks.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-3-4-orc-berserker",
      name: "Orc Berserker",
      monsterType: "brute",
      initiative: 1,
      maxHp: 14,
      notes: "Power strike A frenzied orc that charges into battle, delivering devastating blows with reckless abandon.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-3-4-orc-chieftain",
      name: "Orc Chieftain",
      monsterType: "commander",
      initiative: 5,
      maxHp: 21,
      notes: "Command, Strike, Heroic (3) A cunning orc leader who directs his warriors with brutal efficiency, allowing allies to make extra attacks.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-3-4-hobgoblin-soldier",
      name: "Hobgoblin Soldier",
      monsterType: "soldier",
      initiative: 3,
      maxHp: 11,
      notes: "Polearm A disciplined hobgoblin armed with a halberd, capable of attacking from the second rank.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-3-4-hobgoblin-archer",
      name: "Hobgoblin Archer",
      monsterType: "slayer",
      initiative: 7,
      maxHp: 10,
      notes: "Ranged (2d6) A skilled hobgoblin archer who can deliver precise, damaging shots from a distance.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-3-4-goblin-wolf-rider",
      name: "Goblin Wolf Rider",
      monsterType: "slayer",
      initiative: 7,
      maxHp: 10,
      notes: "Mounted, Move (8,2) Ranged (2d4) A goblin mounted on a snarling wolf, using hit-and-run tactics to strike swiftly.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-3-4-alpha-wolf",
      name: "Alpha Wolf",
      monsterType: "beast",
      initiative: 6,
      maxHp: 11,
      notes: "Power strike A large alpha wolf that leads its pack, allowing allied wolves to make extra attacks.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-3-4-ghoul",
      name: "Ghoul",
      monsterType: "minion",
      initiative: 2,
      maxHp: 6,
      notes: "Life drain A ravenous undead that can scale walls and strike with paralyzing claws.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-3-4-human-guard",
      name: "Human Guard",
      monsterType: "soldier",
      initiative: 3,
      maxHp: 11,
      notes: "Polearm, Strategy, Tough (5) A well-trained human guard armed with a spear, capable of controlling the battlefield.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-3-4-elf-swordsman",
      name: "Elf Swordsman",
      monsterType: "soldier",
      initiative: 3,
      maxHp: 11,
      notes: "Strike, Agility (4), Block (3) A graceful elf warrior who can deliver multiple precise strikes in combat.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-3-4-gnoll",
      name: "Gnoll",
      monsterType: "brute",
      initiative: 1,
      maxHp: 14,
      notes: "Strike, heroic (2) A fierce gnoll that fights with furious anger.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-3-4-harpy",
      name: "Harpy",
      monsterType: "beast",
      initiative: 6,
      maxHp: 11,
      notes: "Fly, Ranged (2d4) A winged creature that can attack from above with screeching songs or talon strikes.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-3-4-ogre",
      name: "Ogre",
      monsterType: "behemoth",
      initiative: 1,
      maxHp: 30,
      notes: "Devastating strike Health (30) Towering brutes swinging tree-trunk clubs, smashing anything in reach.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
  ],
  levels_5_6: [
    {
      id: "default-levels-5-6-orc",
      name: "Orc",
      monsterType: "soldier",
      initiative: 4,
      maxHp: 14,
      notes: "A muscular, green-skinned humanoid with a fierce demeanor, wielding a large axe.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-5-6-ogre",
      name: "Ogre",
      monsterType: "brute",
      initiative: 2,
      maxHp: 18,
      notes: "Power strike, Heroic (2) A towering, hulking creature with thick skin and a massive club, capable of crushing foes with ease.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-5-6-ogre-warlord",
      name: "Ogre Warlord",
      monsterType: "commander",
      initiative: 7,
      maxHp: 27,
      notes: "Command, Power strike Heroic (3), Tough (6) A cunning and brutal ogre chieftain, barking orders to its underlings while wielding a spiked club.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-5-6-mummy",
      name: "Mummy",
      monsterType: "slayer",
      initiative: 9,
      maxHp: 13,
      notes: "Move (4,3), Skeletal Mage (6) A preserved corpse wrapped in linen, animated by necromantic magic to cast debilitating curses and summon swarms of insects.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-5-6-wight",
      name: "Wight",
      monsterType: "slayer",
      initiative: 9,
      maxHp: 13,
      notes: "Power strike, Energy drain A malevolent undead being that drains life with its touch and hurls bolts of dark energy.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-5-6-skeleton-warrior",
      name: "Skeleton Warrior",
      monsterType: "minion",
      initiative: 3,
      maxHp: 8,
      notes: "Skeletal An undead cavalryman on a skeletal horse, wielding a long lance to skewer foes from afar.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-5-6-vampire-spawnling",
      name: "Vampire Spawnling",
      monsterType: "slayer",
      initiative: 10,
      maxHp: 13,
      notes: "Power Strike, Heroic (4) Mage (6), Initiative (10) A lesser vampire with pale skin and elongated fangs, agile and deadly in close combat.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-5-6-harpy",
      name: "Harpy",
      monsterType: "minion",
      initiative: 3,
      maxHp: 8,
      notes: "Fly, Ranged (2d6) A winged monstrosity that uses its enchanting song to beguile and control its prey.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-5-6-harpy-queen",
      name: "Harpy Queen",
      monsterType: "leader",
      initiative: 10,
      maxHp: 17,
      notes: "Fly, Command, Diviner (8) A regal harpy who inspires her kin with magical songs and heals their wounds with her touch.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-5-6-gargoyle",
      name: "Gargoyle",
      monsterType: "brute",
      initiative: 2,
      maxHp: 18,
      notes: "Fly, Tough (6) A grotesque stone figure that can soar through the air and withstand arrows with its rocky hide.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-5-6-griffin-nestling",
      name: "Griffin Nestling",
      monsterType: "beast",
      initiative: 8,
      maxHp: 15,
      notes: "Fly, Strike A juvenile griffin, still growing into its full strength, but already a formidable predator with sharp beak and claws.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
  ],
  levels_7_8: [
    {
      id: "default-levels-7-8-knight-errant",
      name: "Knight Errant",
      monsterType: "soldier",
      initiative: 4,
      maxHp: 17,
      notes: "Tough (6) A disciplined warrior clad in gleaming armor, wielding a lance and bow with precision.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-7-8-blazing-hell-hound",
      name: "Blazing Hell Hound",
      monsterType: "beast",
      initiative: 8,
      maxHp: 18,
      notes: "Penetrating blast (4, 1) Furious charge A fiery canine that leaps through the air, unleashing bursts of flame on its foes.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-7-8-lesser-cerberus",
      name: "Lesser Cerberus",
      monsterType: "behemoth",
      initiative: 2,
      maxHp: 48,
      notes: "Power Strike, Heroic (3) A three-headed hound with thick hides, each head biting with enhanced force.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-7-8-veiled-wraith",
      name: "Veiled Wraith",
      monsterType: "slayer",
      initiative: 9,
      maxHp: 16,
      notes: "Spectral, Life drain A shadowy entity that casts eerie spells and foresees enemy movements.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-7-8-necromancer",
      name: "Necromancer",
      monsterType: "leader",
      initiative: 10,
      maxHp: 21,
      notes: "Mage (10) A gaunt figure cloaked in black, summoning undead minions to fight alongside them.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-7-8-bone-lord",
      name: "Bone Lord",
      monsterType: "commander",
      initiative: 7,
      maxHp: 33,
      notes: "Command, Skeletal Power strike, Heroic (2) A necromancer encased in animated bones, unleashing waves of necrotic energy.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-7-8-tempest-elemental",
      name: "Tempest Elemental",
      monsterType: "minion",
      initiative: 3,
      maxHp: 10,
      notes: "Ranged (2d12), Fly Blast (10, 2), Heroic (2) A swirling mass of wind and lightning, hurling bolts from above.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-7-8-glaring-basilisk",
      name: "Glaring Basilisk",
      monsterType: "behemoth",
      initiative: 2,
      maxHp: 48,
      notes: "Devastating Strike Toughness (8) Heroic (2) A reptilian horror with a petrifying gaze and a crushing tail swipe.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-7-8-bog-lurker-troll",
      name: "Bog Lurker Troll",
      monsterType: "behemoth",
      initiative: 2,
      maxHp: 48,
      notes: "Power Strike, Heroic (2) Ranged (2d10) Toughness (8) A hulking troll that clambers through trees and smashes with slimy fists.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
  ],
  levels_9_10: [
    {
      id: "default-levels-9-10-minotaur",
      name: "Minotaur",
      monsterType: "brute",
      initiative: 3,
      maxHp: 26,
      notes: "Strike, Tough (6) A hulking bull-headed creature that charges into battle with reckless abandon.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-9-10-minotaur-berserker",
      name: "Minotaur Berserker",
      monsterType: "behemoth",
      initiative: 3,
      maxHp: 57,
      notes: "Power strike, Heroic (2) A frenzied minotaur warrior driven by bloodlust, striking with unmatched ferocity.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-9-10-demon-imp",
      name: "Demon Imp",
      monsterType: "minion",
      initiative: 4,
      maxHp: 12,
      notes: "Fly A small, winged imp that harasses foes with quick strikes from above.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-9-10-demon-sorcerer",
      name: "Demon Sorcerer",
      monsterType: "leader",
      initiative: 12,
      maxHp: 24,
      notes: "Mage (8), Fly, Blast (2, d28) Ranged (2d8) A powerful demonic mage commanding dark magics and summoning hellish flames.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-9-10-demon-lieutenant",
      name: "Demon Lieutenant",
      monsterType: "commander",
      initiative: 9,
      maxHp: 39,
      notes: "Fly, Strike, Command Heroic (3) A tactical demon leader mounted on a nightmarish steed, directing its minions with ruthless efficiency.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-9-10-demon-spawn",
      name: "Demon Spawn",
      monsterType: "behemoth",
      initiative: 3,
      maxHp: 57,
      notes: "Fly, Blast (1, 2d8) Heroic (2) A savage, bat-winged creature born from the abyss, tearing into enemies with razor-sharp claws.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-9-10-stone-golem",
      name: "Stone Golem",
      monsterType: "brute",
      initiative: 3,
      maxHp: 26,
      notes: "Toughness (8) A massive construct of rock and magic, delivering earth-shattering blows to any who dare approach.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-9-10-lich",
      name: "Lich",
      monsterType: "leader",
      initiative: 12,
      maxHp: 24,
      notes: "Mage (8), Skeletal, Command An undead sorcerer of immense power, commanding legions of the dead and weaving necrotic spells.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-9-10-grassland-giant",
      name: "Grassland Giant",
      monsterType: "behemoth",
      initiative: 3,
      maxHp: 70,
      notes: "Devastating strike Blast (2, 3d6) Heroic (2), Health (70) A colossal being of immense strength, hurling boulders and stomping foes beneath its feet.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
  ],
  levels_11_12: [
    {
      id: "default-levels-11-12-swamp-troll",
      name: "Swamp Troll",
      monsterType: "behemoth",
      initiative: 3,
      maxHp: 67,
      notes: "Power Strike, Ranged (2d12) Regeneration (2d6) A hulking troll adapted to the swamp, capable of climbing through the dense foliage and delivering powerful blows with its massive limbs.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-11-12-mountain-troll",
      name: "Mountain Troll",
      monsterType: "brute",
      initiative: 3,
      maxHp: 30,
      notes: "Devastating Strike Heroic (2) A massive troll that roams the mountains, scaling cliffs with ease and smashing foes with earth-shattering blows.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-11-12-young-red-dragon",
      name: "Young Red Dragon",
      monsterType: "behemoth",
      initiative: 3,
      maxHp: 67,
      notes: "Fly, Blast (3, 4d8) Heroic (4), Damage (3d8+5) A fierce young red dragon that soars through the skies, blasts enemies with fire, and strikes with deadly precision.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-11-12-red-dragon-wyrmling",
      name: "Red Dragon Wyrmling",
      monsterType: "minion",
      initiative: 4,
      maxHp: 14,
      notes: "Tough (6), Damage (2d6+3) A fierce red dragon wyrmling that has not yet learned to fly but is a furious foe to fight.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-11-12-hill-giant",
      name: "Hill Giant",
      monsterType: "behemoth",
      initiative: 3,
      maxHp: 67,
      notes: "Power Strike, Heroic (3) A towering giant that hurls boulders, smashes foes with its club, and charges into battle on the back of a massive beast, dealing extra damage.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-11-12-ogre",
      name: "Ogre",
      monsterType: "soldier",
      initiative: 5,
      maxHp: 24,
      notes: "Power strike, Heroic (2) A towering, hulking creature with thick skin and a massive club, capable of crushing foes with ease.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-11-12-chain-devil",
      name: "Chain Devil",
      monsterType: "slayer",
      initiative: 11,
      maxHp: 21,
      notes: "Polearm A devil that wields chains with deadly precision, striking from afar and delivering devastating blows that shred armor and flesh.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
  ],
  levels_13_14: [
    {
      id: "default-levels-13-14-wyvern-hatchling",
      name: "Wyvern Hatchling",
      monsterType: "minion",
      initiative: 5,
      maxHp: 16,
      notes: "Fly A young wyvern, still learning to hunt and fight. This weak and fragile hatchling relies on its wings to escape danger rather than engage in prolonged combat.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-13-14-venomous-wyvern",
      name: "Venomous Wyvern",
      monsterType: "slayer",
      initiative: 13,
      maxHp: 24,
      notes: "Fly, Power Strike A wyvern with a venomous sting, capable of delivering deadly blows.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-13-14-elder-wyvern",
      name: "Elder Wyvern",
      monsterType: "behemoth",
      initiative: 4,
      maxHp: 76,
      notes: "Fly, Devastating Strike Heroic (2) An ancient wyvern, its scales hardened by time, delivering crushing blows.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-13-14-chimera",
      name: "Chimera",
      monsterType: "behemoth",
      initiative: 4,
      maxHp: 76,
      notes: "Blast, Strike Heroic (3) A monstrous creature with three heads, unleashing fire and fury upon its foes.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-13-14-guardian-sphinx",
      name: "Guardian Sphinx",
      monsterType: "leader",
      initiative: 14,
      maxHp: 31,
      notes: "Fly, Mage (10) A winged sphinx that casts powerful spells to protect its domain and support its allies.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-13-14-snakefolk-warrior",
      name: "Snakefolk Warrior",
      monsterType: "soldier",
      initiative: 6,
      maxHp: 27,
      notes: "Climber, Polearm A snakefolk warrior that can scale walls and strike with its polearm from unexpected angles. Trained for combat, this agile fighter uses its spear to attack in formation or from elevated positions.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-13-14-snakefolk-captain",
      name: "Snakefolk Captain",
      monsterType: "commander",
      initiative: 11,
      maxHp: 51,
      notes: "Command, Power Strike A cunning snakefolk leader that directs its troops and strikes with precision. This skilled commander boosts its allies' attacks while delivering enhanced strikes of its own.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-13-14-centaur-scout",
      name: "Centaur Scout",
      monsterType: "soldier",
      initiative: 6,
      maxHp: 27,
      notes: "Mounted, Ranged A swift centaur armed with a bow, charging into battle and firing arrows with deadly accuracy. Trained for mobility, this scout uses its equine speed to charge and unleash precise arrow volleys.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-13-14-centaur-chief",
      name: "Centaur Chief",
      monsterType: "commander",
      initiative: 11,
      maxHp: 51,
      notes: "Mounted, Command A powerful centaur leader that inspires its kin and leads charges into enemy lines. This commander enhances its herd's assaults while leveraging its charge for devastating impact.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-13-14-centaur-shaman",
      name: "Centaur Shaman",
      monsterType: "leader",
      initiative: 14,
      maxHp: 31,
      notes: "Diviner (8) A centaur shaman that harnesses the power of nature and peers into the future to aid its allies. Fragile but mystical, this shaman casts spells and foresees events to support its tribe in battle.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
  ],
  levels_15_16: [
    {
      id: "default-levels-15-16-tyrannosaurus",
      name: "Tyrannosaurus",
      monsterType: "beast",
      initiative: 12,
      maxHp: 28,
      notes: "Devastating Strike Heroic (3) This towering predator uses its powerful jaws to crush prey and can scale rocky outcrops with surprising agility.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-15-16-infernal-dreadknight",
      name: "Infernal Dreadknight",
      monsterType: "brute",
      initiative: 4,
      maxHp: 36,
      notes: "Strike, Polearm Clad in blackened armor, this fiendish warrior wields a wicked glaive to strike foes from a distance in formation.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-15-16-infernal-skeletal-knight",
      name: "Infernal Skeletal Knight",
      monsterType: "soldier",
      initiative: 6,
      maxHp: 28,
      notes: "Skeletal, Power Strike A hulking undead knight from the infernal realms, its bony frame shrugs off arrows while delivering crushing blows.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-15-16-infernal-sorcerer",
      name: "Infernal Sorcerer",
      monsterType: "leader",
      initiative: 14,
      maxHp: 35,
      notes: "Mage, Blast A cackling fiend wreathed in flames; this sorcerer hurls explosive hellfire at clusters of enemies.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-15-16-sylvaris-blade",
      name: "Sylvaris Blade",
      monsterType: "soldier",
      initiative: 6,
      maxHp: 28,
      notes: "Ranged (3d8), Strike A disciplined elven warrior, this blade master wields a bow and longsword with deadly precision in quick succession.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-15-16-sylvaris-captain",
      name: "Sylvaris Captain",
      monsterType: "commander",
      initiative: 11,
      maxHp: 57,
      notes: "Command, Polearm A stern elven officer directs troops with tactical brilliance, striking from the second rank with a gleaming spear.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-15-16-sylvaris-mage",
      name: "Sylvaris Mage",
      monsterType: "minion",
      initiative: 5,
      maxHp: 18,
      notes: "Mage (8), Ranged (3d8) A fragile elven apprentice hurls bolts of arcane energy from a safe distance, supporting stronger allies.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
  ],
  levels_17_18: [
    {
      id: "default-levels-17-18-hill-giant",
      name: "Hill Giant",
      monsterType: "brute",
      initiative: 5,
      maxHp: 38,
      notes: "Power Strike, Heroic (3) A towering, brutish giant that charges down hills on a massive boar, smashing foes with relentless force.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-17-18-abyssal-fiend",
      name: "Abyssal Fiend",
      monsterType: "minion",
      initiative: 6,
      maxHp: 19,
      notes: "Ranged (3d6), Blast (1, 3d10) Fly A shrieking, bat-winged demon that hurls fiery blasts from above, scattering weak but numerous attacks across the battlefield.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-17-18-greater-abyssal-fiend",
      name: "Greater Abyssal Fiend",
      monsterType: "soldier",
      initiative: 7,
      maxHp: 29,
      notes: "Strike, Polearm, Skeletal A disciplined infernal warrior wielding a jagged glaive, striking from behind its allies with eerie resilience to arrows.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-17-18-greater-abyssal-prince",
      name: "Greater Abyssal Prince",
      monsterType: "behemoth",
      initiative: 5,
      maxHp: 94,
      notes: "Devastating Strike Toughness A colossal demon lord whose earth-shaking blows and fiery eruptions devastate entire groups of enemies.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-17-18-elderwood-sentinel",
      name: "Elderwood Sentinel",
      monsterType: "beast",
      initiative: 14,
      maxHp: 29,
      notes: "Climber, Power Strike, Diviner A lithe, treelike predator that scales forest canopies, striking with precision guided by glimpses of the future.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-17-18-rootcrusher-ent",
      name: "Rootcrusher Ent",
      monsterType: "brute",
      initiative: 5,
      maxHp: 38,
      notes: "Strike, Behemoth, Skeletal A massive, gnarled tree-beast that uproots the ground with each swing, shrugging off spears with its woody hide.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-17-18-bloodtusk-orc-warrior",
      name: "Bloodtusk Orc Warrior",
      monsterType: "minion",
      initiative: 6,
      maxHp: 19,
      notes: "Mounted, Polearm, Command A snarling orc rider atop a vicious boar, jabbing with a long spear and barking orders to its kin.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-17-18-bloodtusk-warlord",
      name: "Bloodtusk Warlord",
      monsterType: "commander",
      initiative: 13,
      maxHp: 63,
      notes: "Command, Mage, Fly A cunning orc chieftain soaring on a tamed wyvern, weaving spells and directing brutal assaults from the sky.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
  ],
  levels_19_20: [
    {
      id: "default-levels-19-20-fang-titan",
      name: "Fang Titan",
      monsterType: "behemoth",
      initiative: 5,
      maxHp: 103,
      notes: "Devastating strike Heroic (2), Ranged A colossal beast with razor-sharp fangs, capable of unleashing devastating attacks, area blasts, and hurling debris at foes.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-19-20-vampire-lord",
      name: "Vampire Lord",
      monsterType: "leader",
      initiative: 16,
      maxHp: 42,
      notes: "Mage (8), Command, Fly A powerful undead lord with mastery over dark magic, able to command minions and soar through the air.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-19-20-mummy-deathguard",
      name: "Mummy Deathguard",
      monsterType: "soldier",
      initiative: 7,
      maxHp: 30,
      notes: "Power strike, Skeletal A mummified warrior wrapped in ancient bandages, skilled in combat with a polearm and resistant to piercing damage.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-19-20-mummy-deathhound",
      name: "Mummy Deathhound",
      monsterType: "beast",
      initiative: 14,
      maxHp: 30,
      notes: "Strike, Climber A swift and agile undead hound that can scale walls and strike with precision.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-19-20-mummy-deathlord",
      name: "Mummy Deathlord",
      monsterType: "commander",
      initiative: 13,
      maxHp: 70,
      notes: "Command, Mounted Heroic (3) A regal mummified figure riding a spectral steed, directing its minions with strategic commands.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-19-20-sandstorm-necromancer",
      name: "Sandstorm Necromancer",
      monsterType: "leader",
      initiative: 16,
      maxHp: 42,
      notes: "Mage (8) A sinister spellcaster who commands the sands, unleashing destructive storms and raising the dead.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-19-20-angelic-herald",
      name: "Angelic Herald",
      monsterType: "commander",
      initiative: 13,
      maxHp: 70,
      notes: "Command, Fly, Diviner (6) A radiant celestial being that soars above the battlefield, inspiring allies and foreseeing enemy moves.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
  ],
  levels_21_22: [
    {
      id: "default-levels-21-22-storm-giant",
      name: "Storm Giant",
      monsterType: "behemoth",
      initiative: 5,
      maxHp: 113,
      notes: "Blast, Devastating Strike This colossal giant rides a tempestuous thundercloud, unleashing devastating lightning blasts and crushing enemies underfoot.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-21-22-storm-giant-king",
      name: "Storm Giant King",
      monsterType: "commander",
      initiative: 13,
      maxHp: 75,
      notes: "Command, Diviner (12) Clad in electrified armor and wielding a massive trident, this king directs the battlefield with foresight and authority.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-21-22-stormcaller-writher",
      name: "Stormcaller Writher",
      monsterType: "slayer",
      initiative: 15,
      maxHp: 28,
      notes: "Strike A serpentine creature of bone and storm energy, striking with lethal precision and shrugging off piercing blows.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-21-22-stormcaller-beast",
      name: "Stormcaller Beast",
      monsterType: "beast",
      initiative: 14,
      maxHp: 31,
      notes: "Strike A ferocious winged predator crackling with electricity, diving from the skies to rend foes with charged claws.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-21-22-lightning-swarm",
      name: "Lightning Swarm",
      monsterType: "minion",
      initiative: 6,
      maxHp: 20,
      notes: "Ranged (3d6), Fly A buzzing cloud of tiny, sparking motes that swarm and zap anything in their path with erratic bolts.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-21-22-lightning-elemental",
      name: "Lightning Elemental",
      monsterType: "soldier",
      initiative: 7,
      maxHp: 30,
      notes: "Ranged (3d12), Power Strike A humanoid mass of pure lightning, predicting enemy moves and striking with precision bolts from afar.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
  ],
  levels_23_24: [
    {
      id: "default-levels-23-24-undead-legionnaire",
      name: "Undead Legionnaire",
      monsterType: "minion",
      initiative: 6,
      maxHp: 20,
      notes: "Ranged, Skeletal A frail skeletal warrior clad in tattered armor, hurling javelins from decayed hands.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-23-24-cryptborn-enchanter",
      name: "Cryptborn Enchanter",
      monsterType: "leader",
      initiative: 16,
      maxHp: 49,
      notes: "Mage, Blast, Diviner A gaunt figure draped in rotting robes, weaving spells that shatter minds and bolster its allies with cryptic visions.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-23-24-gravehowl-behemoth",
      name: "Gravehowl Behemoth",
      monsterType: "behemoth",
      initiative: 5,
      maxHp: 122,
      notes: "Blast, Tough, Mounted A colossal, rotting beast that unleashes a deafening roar to shatter foes, charging with unstoppable fury when ridden by its master.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-23-24-pitspawn-marauder",
      name: "Pitspawn Marauder",
      monsterType: "soldier",
      initiative: 7,
      maxHp: 30,
      notes: "Strike, Polearm A vicious fiend from the abyss, wielding a jagged glaive to carve through enemy lines with extra ferocity.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-23-24-pitfiend-warbringer",
      name: "Pitfiend Warbringer",
      monsterType: "commander",
      initiative: 13,
      maxHp: 81,
      notes: "Command, Blast, Mounted A horned general astride a flaming steed, barking orders to its minions while unleashing fiery bursts upon the battlefield.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
  ],
  levels_25_26: [
    {
      id: "default-levels-25-26-ashmaw-dragon",
      name: "Ashmaw Dragon",
      monsterType: "behemoth",
      initiative: 5,
      maxHp: 131,
      notes: "Ranged (4d12), Fly Devastating Strike Penetrating Blast (4, 4d12) Heroic (4) A massive dragon with ash-gray scales, it spews fiery breath and strikes with deadly precision from the skies.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-25-26-scorchveil-marauder",
      name: "Scorchveil Marauder",
      monsterType: "slayer",
      initiative: 16,
      maxHp: 28,
      notes: "Strike, Devastating Strike, Climber A swift and ruthless killer cloaked in shimmering heat; it scales walls to deliver lethal, bone-shattering blows.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-25-26-scorchveil-master",
      name: "Scorchveil Master",
      monsterType: "commander",
      initiative: 13,
      maxHp: 87,
      notes: "Command, Mage (4) A cunning tactician wielding a blazing polearm, it directs allies with precision and unleashes fiery spells on foes.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-25-26-oblivion-behemoth",
      name: "Oblivion Behemoth",
      monsterType: "behemoth",
      initiative: 5,
      maxHp: 131,
      notes: "Blast, Devastating Strike, Skeletal A towering monstrosity of bone and shadow, it crushes entire groups with sweeping blows and shrugs off piercing strikes.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
  ],
  levels_27_28: [
    {
      id: "default-levels-27-28-fleetbreaker-kraken",
      name: "Fleetbreaker Kraken",
      monsterType: "behemoth",
      initiative: 5,
      maxHp: 140,
      notes: "Ranged, Blast (3, 3d12) Heroic (4) A colossal squid-like beast with tentacles that shatter ships and hurl deadly barrages of water and debris across the battlefield.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-27-28-abyssal-serpent",
      name: "Abyssal Serpent",
      monsterType: "beast",
      initiative: 14,
      maxHp: 34,
      notes: "Strike, Climber A sinuous, deep-sea predator that slithers up cliffs and strikes with lightning-fast bites, tearing through armor with ease.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-27-28-tidalcrusher-octopus",
      name: "Tidalcrusher Octopus",
      monsterType: "brute",
      initiative: 5,
      maxHp: 40,
      notes: "Power Strike A massive octopus that churns the seas into a maelstrom, crushing foes with its powerful arms and slamming multiple enemies at once.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-27-28-ocean-lord",
      name: "Ocean Lord",
      monsterType: "leader",
      initiative: 16,
      maxHp: 57,
      notes: "Mage (6), Command Heroic (2) A regal merfolk sovereign wielding ancient sea magic, calling forth waves to smite foes while inspiring allies to fight with renewed vigor.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-27-28-rotwing-carrion",
      name: "Rotwing Carrion",
      monsterType: "slayer",
      initiative: 16,
      maxHp: 28,
      notes: "Fly, Power Strike, Skeletal A grotesque, undead vulture with tattered wings, diving from the skies to rip apart prey with enhanced, bone-shattering strikes.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-27-28-rotwing-gargarion",
      name: "Rotwing Gargarion",
      monsterType: "commander",
      initiative: 13,
      maxHp: 93,
      notes: "Fly, Command, A cunning, skeletal harpy-like creature that soars above the fray, directing its minions with eerie foresight and shrieking commands.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
  ],
  levels_29_30: [
    {
      id: "default-levels-29-30-worldbreaker-dragon",
      name: "Worldbreaker Dragon",
      monsterType: "behemoth",
      initiative: 5,
      maxHp: 149,
      notes: "Fly, Devastating Strike Penetrating Blast (5, 4d12) Heroic (4) A colossal dragon with scales like shattered stone, its fiery breath and earth-shaking tail obliterate all in its path.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-29-30-hellforge-titan",
      name: "Hellforge Titan",
      monsterType: "behemoth",
      initiative: 5,
      maxHp: 149,
      notes: "Power Strike A towering construct of molten metal and bone, forged in infernal flames to crush foes with relentless force.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-29-30-infernal-legionmaster",
      name: "Infernal Legionmaster",
      monsterType: "commander",
      initiative: 13,
      maxHp: 99,
      notes: "Command, Mage (5) A cunning demonic general clad in spiked armor, directing its minions with dark magic and a wicked glaive.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
    {
      id: "default-levels-29-30-voidspawn",
      name: "Voidspawn",
      monsterType: "slayer",
      initiative: 16,
      maxHp: 28,
      notes: "Ranged (3d12), Strike A shadowy entity from the abyss, wielding eerie tendrils and prophetic curses to unravel its enemies' fates.",
      createdAt: DEFAULT_TEMPLATE_TIMESTAMP,
      updatedAt: DEFAULT_TEMPLATE_TIMESTAMP,
    },
  ],
};
